services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"

  node:
    build: .
    container_name: node_app
    ports:
      - "3001:3000"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - AWS_S3_ENDPOINT=http://minio:9000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - minio
      - init

  init:
    image: minio/mc
    container_name: minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do sleep 1; done &&
      (/usr/bin/mc mb -p myminio/my-development-bucket || true)
      "

volumes:
  minio_data:
  minio_config:
